spring.application.name=Platform

spring.datasource.url = jdbc:mysql://localhost:3306/smartstudentdb
spring.datasource.username = root
spring.datasource.password = Aman2212@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${JAVA_MAIL_ACCOUNT}
spring.mail.password=${JAVA_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google GenAI API Key
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
# Chat Model
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

